### ISSUE TITLE
Rename .js files containing JSX to .jsx

### ISSUE THREAD

**Issue by santiment-admin** [santiment/SantimentMobile#60]

**Comment by santiment-admin** [comment]
Probably all the files of scenes and components.

**Comment by santiment-admin** [comment]
https://github.com/airbnb/javascript/tree/master/react#naming

**Comment by igormatyushkin014** [comment]
@santiment-admin `.jsx` files are not found by compiler. As some people from StackOverflow [say](https://stackoverflow.com/questions/30685892/require-jsx-in-react-native), we have to change some files in `node_modules/react-native` folder, which obviously is not a good solution because those files will be overwritten by closest update.

![simulator screen shot 29 2017 22 49 55](https://cloud.githubusercontent.com/assets/8403399/26560846/32f929a6-44c2-11e7-89ad-bc301142ec11.png)

**Comment by santiment-admin** [comment]
Then it's not worth doing. Closing.
